### ISSUE TITLE
local time issue with the JSS server and client.

### ISSUE THREAD

**Issue by vijayasekharn** [jamf/JSSBinarySelfHeal#4]
Hi All
It's not an issue. If add this error resolution on this package, It will have more client resolution.

Issue: 
If Time has changed in Mac, recon command won't execute. Below is the error message. 
Also, any policy could not execute because Mac did not connect to JSS server.

Resolution: 
Until the change time manually or with below command might configure again. So could you add this scenario as well in this package?
setnetworktimeserver

Error message: 

     There was an error. Clock Skew Error - There is a discrepancy between the local time and the JSS server time.

**Comment by cyvan31** [comment]
I will look into this today.  Thank you for reaching out.

Best regards,

Lucas Vance
Jamf
Strategic Technical Account Manager
General Support: 612-216-1296

On Jun 12, 2017, at 11:39 AM, vijayasekharn <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi All
It's not an issue. If add this error resolution on this package, It will have more client resolution.

Issue:
If Time has in Mac, recon command won't execute. Below is the error message.
Also, any policy could not execute because Mac did not connect to JSS server.

Resolution:
Until the change time manually or with below command might configure again. So could you add this scenario as well in this package?
setnetworktimeserver

Error message:

 There was an error. Clock Skew Error - There is a discrepancy between the local time and the JSS server time.

**Comment by vijayasekharn** [comment]
HI GitHub

yes in my environment there time server those based on reason.
(Sorry Don't your exact name)


Best Regards

Vijayasekhar Naidu

M + 91 8197353583


________________________________

**Comment by cyvan31** [comment]
Hi,

My name is Lucas and I am the author of the self heal.  I have made a code change to add the network time server into the self heal verification.  Please let me know if the current code change suffices the ask for adding this check.

Best regards,

Lucas Vance
Jamf
Strategic Technical Account Manager
General Support: 612-216-1296

On Jun 15, 2017, at 1:41 AM, vijayasekharn <notifications@github.com<mailto:notifications@github.com>> wrote:


HI GitHub

yes in my environment there time server those based on reason.
(Sorry Don't your exact name)


Best Regards

Vijayasekhar Naidu

M + 91 8197353583


________________________________
